### PR TITLE
Resolve Issue with Gentest

### PR DESCRIPTION
**Pull request by joelowj**
Resolve problem Exception in thread "main" sav.common.core.SavRtException: class not found - [LString;

### CODE REVIEW

**Comment by llmhyy** [comment]
@joelowj could you kindly explain why the fix is necessary or how the original bug occurs so that I can approve your pull request?

**Comment by joelowj** [comment]
When I was working on Gentest, whenever methods with method argument of String[],
will generate Exception in thread "main" sav.common.core.SavRtException: class not found - [LString;

It appears that the original code in sav.common.core.utils.SignatureUtils.getSignature, will return LString;

In order to resolve the issue getSignature should return Ljava.lang.Sring; 
You can refer to the screenshot below, it appears that Gentest could not clear all the testcases.
Throwing the error Exception in thread "main" sav.common.core.SavRtException: class not found - [LString; With the changes made, it cleared all the test cases.

I check the call hierarchy of the original getSignature, it seems that there were some other dependencies on it. I did a simple method overload on getSignature to make sure the changes does not affect the other projects depending on the original getSignature.

imageoriginal3
imagechanges3

imageoriginal2
imagechanges2

**Comment by joelowj** [comment]
Hi, yup I understand the fix I have provided was not a great one. 
Thank you so much for the explanation. I will work on it and submit a pull request with the appropriate fix. 
Ya, I noticed the comments provided by the author of this piece of code.
In that case, would you suggest that I do another method overloading so that that method return by the author still works for other projects which uses that method.[](url)

**Comment by joelowj** [comment]
@llmhyy Hi, thx for the valuable advise. Indeed the fix was not a great one.

However, before I made that fix. I initially change the code to return "L" + className.replace('.', '/') + ";";
I ran the test several times and there seems to create some issue with the performance of Gentest and the latter fix that I made seem to resolve the performance issue. You can take a look at the screen shot.

In your opinion, should we continue with the proposed fix since the performance of Gentest seems to become slower? If you're good, I will make the fix and send a pull request.

faster
performance issue

**Comment by llmhyy** [comment]
@joelowj Thanks a lot for your helpful explanation. I checked the code and find that your fix makes the some test cases passed indeed, however, it does not seem to be a "good" fix. I am not going to do demoralize you, as a matter of fact, your submission of pull request does help us a lot indeed! Now, I will explain the case as follows:

The exception you reported origins at line 60 of `VarArrayType.java`, in which a L[java.lang.String; rather than LString; should be reported. With your gut feeling, you change the returned string from `SignatureUtil.getSignature()`. However, you may observe that the returned string should be replaced its '/' char with '.', which means the format of original signature should contain '/'. In addition, you may check the JVM signature format in [https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html](url). 

```
            try {
				if (componentType.isArray()) {
					className = "[" + componentType.getRawType().getName();
				} else {
					className = "[" + SignatureUtils.getSignature(
									componentType.getRawType()).replace('/', '.');
				}
				rawType = Class.forName(className);
			} catch (ClassNotFoundException e) {
				throw new SavRtException("class not found - " + className);
			}
```
Therefore, a more appropriate solution, from my point of view, is to change the `SignatureUtil.getSignature()` method to return a full-qualified class name as follows:
```
public static String getSignature(String className) {
		// not correct, use for method in assertion generation
//		return "L" + className.replace('.', '/') + ";";
//		int i = className.lastIndexOf('.');
//		if (i != -1) {
//			className = className.substring(i + 1);
//		}
		return "L" + className.replace('.', '/') + ";";
	}
```

Nevertheless, my remaining concern is that the author of this piece of code @lylytran left a comment that simply returning the full-qualified name is not correct (see the comments on the above code). So, I am not sure whether such a fix is totally free of problem. 

Nevertheless, I think we may start with such a fix and see what will happens or what bug may occur afterwards. Would you please fix the bug as I mentioned? I will approve your new pull request after you submit it. Thanks!

**Comment by llmhyy** [comment]
@joelowj  

Thanks for your update. I just saw your message just now. I further check the performance issue you mentioned. Based on my observation, these test cases are incomplete. In other words, if these test cases are executed without any reported exception, these test cases will be reported as "passed". The code `"L" + className.replace('.', '/') + ";";` has different behavior with the code `"L" + className + ";";`, therefore, their execution consequence shall be different even if both of them do not incur any reported exception. Given that fact, I think `"L" + className + ";";` would more likely to be buggy.

Hence, I would suggest that let's use the code `"L" + className.replace('.', '/') + ";";` :)

Thanks again for your valuable update and we are looking forward to your new pull request.

**Comment by llmhyy** [comment]
@joelowj

Thanks for your update. I just saw your message just now. I further check the performance issue you mentioned. Based on my observation, these test cases are incomplete. In other words, if these test cases are executed without any reported exception, these test cases will be reported as "passed". The code `"L" + className.replace('.', '/') + ";";` has different behavior with the code `"L" + className + ";";`, therefore, their execution consequence shall be different even if both of them do not incur any reported exception. Given that fact, I think `"L" + className + ";";` would more likely to be buggy.

Hence, I would suggest that let's use the code "L" + className.replace('.', '/') + ";"; :)

Thanks again for your valuable update and we are looking forward to your new pull request.

> @llmhyy Hi, thx for the valuable advise. Indeed the fix was not a great.
> 
> However, before I made that fix. I initially change the code to return "L" + className.replace('.', '/') + ";";
> I ran the test several times and there seems to create some issue with the performance of Gentest and the latter fix that I made seem to resolve the performance issue. You can take a look at the screen shot.
> 
> In your opinion, should we continue with the proposed fix since the performance of Gentest seems to become slower? If you're good, I will make the fix and send a pull request.
> 
> faster
> performance issue

**Comment by joelowj** [comment]
Hi @llmhyy, oh right, that make sense. Sorry, that was an oversight on my part. 
Thank you so much for the valuable advise. I have make the fix accordingly.

**Pull request merged**
